version: "3.8"

networks:
  general:
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
  database:

services:  
  tg-nginx:
    container_name: tg-nginx
    build:
      context: ./docker
      dockerfile: nginx.docker
    networks: 
      general:
        ipv4_address: 172.16.239.10
    volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    - ./docker/nginx/logs:/var/log/nginx/
    - ./app/:/var/www
    ports:
    - "8989:80"
    #- "443:443"
    tty: true
    

  tg-php:
    container_name: tg-php
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    networks: 
      general:
        ipv4_address: 172.16.239.11
      database:
    volumes:
      - ./app/:/var/www
    environment:
      - "UPLOAD_LIMIT=20M"
    tty: true

  # php-cli:
  #   container_name: php-cli
  #   build:
  #     context: ./
  #     dockerfile: docker/php-cli.docker
  #   networks: 
  #     general:
  #       ipv4_address: 172.16.238.12
  #     database:
  #   volumes:
  #     - ./app/:/var/www
  #   environment:
  #     - "UPLOAD_LIMIT=20M"
  #     - "DB_PORT=3306"
  #     - "DB_HOST=mysql"
  #   tty: true

  # node:
  #   container_name: node
  #   networks: 
  #     general:
  #       ipv4_address: 172.16.238.14
  #   build:
  #     context: ./
  #     dockerfile: docker/node.docker
  #   volumes:
  #     - ./app/:/var/www
  #   tty: true

  # mysql:
  #   container_name: mysql
  #   image: mysql:5.7
  #   command: --sql_mode="ONLY_FULL_GROUP_BY"
  #   networks: 
  #     - database
  #   volumes: 
  #     - ./docker/images/mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #     - MYSQL_DATABASE=app
  #     - MYSQL_HOST= mysql
  #     - MYSQL_USER=app
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_PORT=3306
  #   ports:
  #     - "33061:3306"
  #   tty: true

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: corbinu/docker-phpmyadmin
  #   networks: 
  #     - database
  #   ports:
  #       - 8681:80
  #   environment:
  #       MYSQL_USERNAME: app
  #       MYSQL_ROOT_PASSWORD: secret
  #       MYSQL_PORT_3306_TCP_ADDR: mysql
  #   tty: true

  